version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./:/app
    extra_hosts:  # Solo necesario en Linux
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - my_network
networks:
  my_network:
    external: true